[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.16"  # 确保使用最新版本
tokio = { version = "1", features = ["full"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }